### ISSUE TITLE
"Warning: No instances were classified as negative" in ML Results

### ISSUE THREAD

**Issue by amschu** [ShiuLab/ML-Pipeline#20]
For Random Forest (RF) ML Results output, there is a warning stating **`Warning: No instances were classified as negative!`**

In the same output file, the Test Set Scores indicate a 0.5 accuracy and precious scores showing that 50% were negative and 50% positive. 
```
Test Set Scores:
Precision: 0.500000
Accuracy: 0.500000
F1: 0.666667
AUC-ROC: 0.622361 (+/- stdev 0.005668)
AUC-PRC: 0.610843 (+/- stdev 0.005896)
```
There is also a line that would support the file having a balanced set of 7448 instances for each of the 1 or 0 classes. The warning should not be present since there are instances that have the 0 class and the model should be able to predict a negative class with the provided instances.
```
CLASSES: [0 1]
POS: 1 type:  <class 'int'>
NEG: 0 type:  <class 'int'>
```
Balanced dataset will have 7448 instances of each class`

In the RF_results output file it does show no negatives being predicted:

`Count and percent of instances of each class (row) predicted as a class (col):`
```
Class	1	n_total	0_perc	1_perc
0	328562	328562	0	1.0
1	8277	8277	0	1.0
```

This warning can be done by using a subset of the data:
[subset_matrixdata_CM_GitIssue.csv](https://github.com/ShiuLab/ML-Pipeline/files/7017238/subset_matrixdata_CM_GitIssue.csv)

1. ML_preprocess.py: `python /ML-Pipeline/ML_preprocess.py -df subset_matrixdata_CM_GitIssue.csv -sep ',' -onehot f`
2. test_set.py: `python /ML-Pipeline/test_set.py -df subset_matrixdata_CM_GitIssue.csv_mod.txt -sep ',' -type c -p 0.1 -save <test_set_file.txt>`
3. ML_classification.py: `python /ML-Pipeline/ML_classification.py -df subset_matrixdata_CM_GitIssue.csv_mod.txt -sep ',' -test <test_set_file.txt> -cl_train 1,0 -alg RF -cm t -plots t -n_jobs 8`

**Comment by serenalotreck** [comment]
Error running this subset:
```
===>  Grid search started  <===
Traceback (most recent call last):
  File "../../ML-Pipeline/ML_classification.py", line 786, in <module>
    main()
  File "../../ML-Pipeline/ML_classification.py", line 288, in main
    args.gs_full)
  File "/mnt/ufs18/home-118/lotrecks/Shiu_lab/ML-Pipeline/ML_functions.py", line 122, in GridSearch
    temp = df[df['Class'] == cl].sample(min_size, random_state=j)
  File "/opt/software/Python/3.6.4-foss-2018a/lib/python3.6/site-packages/pandas/core/generic.py", line 4995, in sample
    locs = rs.choice(axis_length, size=n, replace=replace, p=weights)
  File "mtrand.pyx", line 894, in numpy.random.mtrand.RandomState.choice
ValueError: a must be greater than 0 unless no samples are taken
```

**Comment by serenalotreck** [comment]
Notes: 
* If the `-cl_train` argument is not `1,0`, then the classes don't get changed to ints, and just stay as strings (Lines 125-130 in `ML_classification.py`). This causes problems for subsetting the data if the classes are ints in the feature table (Line 122 in `ML_functions.py`). Unclear whether this behavior is desired or not, should contact Christina to check if there is a reason for this. 
* Subset doesn't actually reproduce warning: the warning isn't there, and the validation and test results are normal.
* Warning is produced on line 661 of `ML_classification.py`, and is triggered if there is an exception triggered when trying to calculate the percentage of instances classified as negative. The calculation is the number of instances classified as negative, divided by the total number of instances. It is unclear to me why this would ever cause an exception, as the 0 would not be in the denominator. 
* Additionally, there is no exception type specified in the `except` clause. This means that this clause will be executed for any exception, which potentially means that it would tell you there were no negative instances when in fact there were, but there was some other exception (see [this post](https://docs.quantifiedcode.com/python-anti-patterns/correctness/no_exception_type_specified.html) about why specifying an excpetion type is preferrable)

**Comment by serenalotreck** [comment]
I added print statements and a traceback print to the `try/except` clause to see if I could figure out what was causing the exception, and got the following: 
```
Exception type that led to this clause is:
0
Traceback (most recent call last):
  File "/mnt/home/lotrecks/anaconda3/envs/kg/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 2131, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 2140, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../../../ML-Pipeline/ML_classification.py", line 657, in main
    summary_df_proba[NEG])
  File "/mnt/home/lotrecks/anaconda3/envs/kg/lib/python3.8/site-packages/pandas/core/frame.py", line 3455, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/mnt/home/lotrecks/anaconda3/envs/kg/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 0
Warning: No instances were classified as negative!
```
Based on where I placed print statements, this indicates that the exception is actually happening in the line that gets the total number of instances predicted (Line 654 in `ML_classification.py`), *not* the line that calculates the percentage of instances classified as negative, as I originally thought.

**Comment by serenalotreck** [comment]
Conclusion after looking at the subset (which doesn't have this error) and the full dataset (which does) is that this isn't a pipeline problem, and the model is actually predicting everything as the positive class when it gives this warning. It is normal for precision and accuracy to both be 0.5 when all instances in a balanced dataset are predicted as one class.
